#ifndef TI_MSP_DL_CONFIG_H
#define TI_MSP_DL_CONFIG_H

#define CONFIG_MSPM0G350X
#define CONFIG_MSPM0G3507

#include <stdbool.h>
#include <stdint.h>
#include <ti/devices/msp/msp.h>
#include <ti/driverlib/driverlib.h>
#include <ti/driverlib/m0p/dl_core.h>

#ifdef __cplusplus
extern "C" {
#endif

#define CPUCLK_FREQ 32000000U

/* Current A/B motor test wiring. */
#define MOTOR_STBY_PORT GPIOB
#define MOTOR_STBY_PIN  DL_GPIO_PIN_7
#define MOTOR_STBY_IOMUX IOMUX_PINCM24

#define MOTOR_AIN1_PORT GPIOB
#define MOTOR_AIN1_PIN  DL_GPIO_PIN_6
#define MOTOR_AIN1_IOMUX IOMUX_PINCM23

#define MOTOR_AIN2_PORT GPIOB
#define MOTOR_AIN2_PIN  DL_GPIO_PIN_9
#define MOTOR_AIN2_IOMUX IOMUX_PINCM26

#define MOTOR_PWMA_PORT GPIOB
#define MOTOR_PWMA_PIN  DL_GPIO_PIN_8
#define MOTOR_PWMA_IOMUX IOMUX_PINCM25

#define MOTOR_BIN1_PORT GPIOA
#define MOTOR_BIN1_PIN  DL_GPIO_PIN_13
#define MOTOR_BIN1_IOMUX IOMUX_PINCM35

#define MOTOR_BIN2_PORT GPIOA
#define MOTOR_BIN2_PIN  DL_GPIO_PIN_12
#define MOTOR_BIN2_IOMUX IOMUX_PINCM34

#define MOTOR_PWMB_PORT GPIOB
#define MOTOR_PWMB_PIN  DL_GPIO_PIN_26
#define MOTOR_PWMB_IOMUX IOMUX_PINCM57

#define MOTOR_CIN1_PORT GPIOA
#define MOTOR_CIN1_PIN  DL_GPIO_PIN_10
#define MOTOR_CIN1_IOMUX IOMUX_PINCM21

#define MOTOR_CIN2_PORT GPIOA
#define MOTOR_CIN2_PIN  DL_GPIO_PIN_11
#define MOTOR_CIN2_IOMUX IOMUX_PINCM22

#define MOTOR_PWMC_PORT GPIOB
#define MOTOR_PWMC_PIN  DL_GPIO_PIN_12
#define MOTOR_PWMC_IOMUX IOMUX_PINCM29

#define MOTOR_DIN1_PORT GPIOB
#define MOTOR_DIN1_PIN  DL_GPIO_PIN_13
#define MOTOR_DIN1_IOMUX IOMUX_PINCM30

#define MOTOR_DIN2_PORT GPIOB
#define MOTOR_DIN2_PIN  DL_GPIO_PIN_3
#define MOTOR_DIN2_IOMUX IOMUX_PINCM16

#define MOTOR_PWMD_PORT GPIOB
#define MOTOR_PWMD_PIN  DL_GPIO_PIN_2
#define MOTOR_PWMD_IOMUX IOMUX_PINCM15

#define TRACK_X1_PORT GPIOA
#define TRACK_X1_PIN  DL_GPIO_PIN_26
#define TRACK_X1_IOMUX IOMUX_PINCM59

#define TRACK_X2_PORT GPIOA
#define TRACK_X2_PIN  DL_GPIO_PIN_27
#define TRACK_X2_IOMUX IOMUX_PINCM60

#define TRACK_X3_PORT GPIOA
#define TRACK_X3_PIN  DL_GPIO_PIN_24
#define TRACK_X3_IOMUX IOMUX_PINCM54

#define TRACK_X4_PORT GPIOA
#define TRACK_X4_PIN  DL_GPIO_PIN_25
#define TRACK_X4_IOMUX IOMUX_PINCM55

#define TRACK_X5_PORT GPIOB
#define TRACK_X5_PIN  DL_GPIO_PIN_24
#define TRACK_X5_IOMUX IOMUX_PINCM52

#define TRACK_X6_PORT GPIOB
#define TRACK_X6_PIN  DL_GPIO_PIN_25
#define TRACK_X6_IOMUX IOMUX_PINCM56

#define TRACK_X7_PORT GPIOA
#define TRACK_X7_PIN  DL_GPIO_PIN_22
#define TRACK_X7_IOMUX IOMUX_PINCM47

#define TRACK_X8_PORT GPIOB
#define TRACK_X8_PIN  DL_GPIO_PIN_20
#define TRACK_X8_IOMUX IOMUX_PINCM48

#define KEY_START_PORT GPIOA
#define KEY_START_PIN  DL_GPIO_PIN_18
#define KEY_START_IOMUX IOMUX_PINCM40

#define LED_PORT GPIOB
#define LED_PIN  DL_GPIO_PIN_18
#define LED_IOMUX IOMUX_PINCM44

#define BEEP_PORT GPIOA
#define BEEP_PIN  DL_GPIO_PIN_21
#define BEEP_IOMUX IOMUX_PINCM46

void SYSCFG_DL_init(void);

#ifdef __cplusplus
}
#endif

#endif
