#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include "ti_msp_dl_config.h"

#define TRACK_BLACK_IS_HIGH 1U
#define TRACK_X1_IS_LEFT 0U

#define APP_MODE_SAFE_IDLE 0U
#define APP_MODE_ENCODER_DIAGNOSTIC 1U
#define APP_MODE_SPEED_TUNE 2U
#define APP_MODE_LINE_GYRO 3U
#define APP_MODE_SQUARE_3LOOP 4U
#define APP_MODE_CHASSIS_CALIBRATION 5U
#define APP_RUN_MODE APP_MODE_SQUARE_3LOOP

/* Enable only after a complete, verified chassis calibration run. */
#define USE_STORED_CHASSIS_CALIBRATION 1U

#define MOTOR_CHANNEL_TEST 0U
#define POWER_SWITCH_TEST 0U
#define POWER_SWITCH_TEST_DUTY_PERCENT 100U
#define POWER_SWITCH_ACTIVE_HIGH 1U
#define POWER_SWITCH_PWM_PERIOD_MS 10U
#define POWER_SWITCH_MAX_DUTY_PERCENT 100U
#define POWER_SWITCH_MAX_ON_MS 30000U

#if ((POWER_SWITCH_TEST + MOTOR_CHANNEL_TEST) > 1U)
#error "Enable only one hardware test mode at a time"
#endif

#if (APP_RUN_MODE > APP_MODE_CHASSIS_CALIBRATION)
#error "APP_RUN_MODE is invalid"
#endif

#if (POWER_SWITCH_TEST_DUTY_PERCENT > 100U)
#error "POWER_SWITCH_TEST_DUTY_PERCENT must not exceed 100"
#endif
#define PWM_PERIOD_TICKS 200U
#define MOTOR_PWM_TIMER_PERIOD 1600U
#define MOTOR_TEST_DUTY 160U

#define CONTROL_TICK_MS 1U
#define SPEED_CONTROL_PERIOD_MS 10U
#define LINE_CONTROL_PERIOD_MS 5U
#define IMU_HEADING_PERIOD_MS 5U

/* Normalize this IMU mounting orientation to the chassis yaw convention. */
#define IMU_HEADING_SIGN (-1)

#define ENCODER_LEFT_SIGN (-1)
#define ENCODER_RIGHT_SIGN 1

#define LINE_BASE_LEFT_DUTY 40U
#define LINE_BASE_RIGHT_DUTY 40U
#define LINE_KP 6
#define LINE_KD 1
#define LINE_CENTER_MASK 0x18U
#define LINE_LOST_LEFT_DUTY 44U
#define LINE_LOST_RIGHT_DUTY 36U

#define GYRO_HEADING_KP 2
#define GYRO_HEADING_CORR_DIV 900
#define GYRO_HEADING_CORR_MAX 6
#define GYRO_DEAD_RAW 8
#define GYRO_FAIL_LIMIT_MS 100U
#define GYRO_PWM_TICKS_PER_PERCENT (PWM_PERIOD_TICKS / 100U)

#define START_BOOST_LEFT_DUTY 60U
#define START_BOOST_RIGHT_DUTY 60U
#define START_BOOST_MS 180U
#define KEY_DEBOUNCE_MS 30U
#define KEY_RELEASE_ARM_MS 50U

/* Initial 3-loop values; tune after encoder PPR and chassis dimensions. */
#define SPEED_PID_KP 18
#define SPEED_PID_KI 3
#define SPEED_PID_KD 0
#define SPEED_PID_SCALE 10
#define SPEED_PID_OUTPUT_LIMIT 35
#define SPEED_PWM_HARD_LIMIT 35
#define SPEED_PID_INTEGRAL_LIMIT 1200
#define SPEED_FEEDFORWARD_PER_TICK 2
#define WHEEL_SPEED_TARGET_LIMIT 20
#define SPEED_TARGET_SLEW_TICKS 1
#define SPEED_TUNE_TARGET_TICKS 2
#define ENCODER_WATCHDOG_MIN_PWM 20
#define ENCODER_NO_FEEDBACK_TIMEOUT_MS 800U
#define ENCODER_DIRECTION_FAULT_MS 300U
#define ENCODER_OVERSPEED_TICKS 30

#define SQUARE_LINE_PID_KP 4
#define SQUARE_LINE_PID_KI 0
#define SQUARE_LINE_PID_KD 1
#define SQUARE_LINE_PID_SCALE 8
#define SQUARE_LINE_CORR_LIMIT 3
#define SQUARE_LINE_EDGE_ERROR 7
#define SQUARE_LINE_CENTER_RELEASE_CYCLES 1U
#define SQUARE_LINE_MEDIUM_ERROR 3
#define SQUARE_LINE_LARGE_ERROR 5
#define SQUARE_LINE_MEDIUM_SPEED_TICKS 7
#define SQUARE_LINE_LARGE_SPEED_TICKS 5

#define SQUARE_DISTANCE_PID_KP 8
#define SQUARE_DISTANCE_PID_KI 0
#define SQUARE_DISTANCE_PID_KD 12
#define SQUARE_DISTANCE_PID_SCALE 10

#define SQUARE_HEADING_PID_KP 6
#define SQUARE_HEADING_PID_KI 0
#define SQUARE_HEADING_PID_KD 12
#define SQUARE_HEADING_PID_SCALE 1000

#define SQUARE_CRUISE_SPEED_TICKS 8
#define SQUARE_APPROACH_MAX_SPEED_TICKS 2
#define SQUARE_CORNER_OFFSET_TRIM_MM 20U
#define SQUARE_SPEED_RAMP_STEP_MS 150U
#define SQUARE_TURN_MAX_SPEED_TICKS 3
#define SQUARE_TURN_MIN_SPEED_TICKS 1
#define SQUARE_TURN_START_SPEED_TICKS 8
#define SQUARE_TURN_START_BOOST_MS 400U
#define SQUARE_TURN_START_MAX_ANGLE_MDEG 10000
#define SQUARE_CORNER_DEBOUNCE_MS 3U
#define SQUARE_CORNER_SIDE_X1_MASK 0x07U
#define SQUARE_CORNER_SIDE_X8_MASK 0xE0U
#define SQUARE_CORNER_MIN_TRAVEL_MM 650
#define SQUARE_CORNER_MIN_TRAVEL_MS 2500U
#define SQUARE_CORNER_LOST_DEBOUNCE_MS 80U
#define SQUARE_CORNER_ARM_MS 500U
#define SQUARE_CORNER_CLEAR_MS 30U
#define SQUARE_LINE_LOST_TIMEOUT_MS 300U
#define SQUARE_DISTANCE_TOLERANCE_TICKS 8
#define SQUARE_STOP_SPEED_TOLERANCE 0
#define SQUARE_STOP_SETTLE_MS 150U
#define SQUARE_PRE_TURN_PAUSE_MS 400U
#define SQUARE_TURN_DIRECTION (-1)
#define SQUARE_TURN_ANGLE_MDEG 90000
#define SQUARE_HEADING_TOLERANCE_MDEG 1500
#define SQUARE_TURN_SETTLE_MS 80U
#define SQUARE_TURN_TIMEOUT_MS 5000U
#define SQUARE_IMU_FAIL_LIMIT 5U
#define SQUARE_TURN_CAPTURE_CLEAR_MS 20U
#define SQUARE_TURN_CAPTURE_MIN_ANGLE_MDEG 78000
#define SQUARE_TURN_CAPTURE_DEBOUNCE_MS 8U
#define SQUARE_REACQUIRE_DEBOUNCE_MS 8U
#define SQUARE_REACQUIRE_SETTLE_MS 40U
#define SQUARE_REACQUIRE_SCAN_DELAY_MS 80U
#define SQUARE_REACQUIRE_SCAN_HALF_MS 550U
#define SQUARE_REACQUIRE_SCAN_ANGLE_MDEG 16000
#define SQUARE_REACQUIRE_FORWARD_SPEED_TICKS 3
#define SQUARE_REACQUIRE_MAX_SPEED_TICKS 3
#define SQUARE_REACQUIRE_MIN_SPEED_TICKS 1
#define SQUARE_REACQUIRE_SCAN_BOOST_SPEED_TICKS 6
#define SQUARE_REACQUIRE_SCAN_BOOST_MS 250U
#define SQUARE_REACQUIRE_BOOST_RELEASE_MDEG 8000
#define SQUARE_REACQUIRE_TIMEOUT_MS 6000U
#define SQUARE_CONTINUOUS_RUN 1U
#define SQUARE_TOTAL_CORNERS 4U

/* Empirical chassis calibration profile. */
#define CAL_STRAIGHT_SPEED_TICKS 3
#define CAL_OFFSET_SPEED_TICKS 1
#define CAL_TURN_SPEED_TICKS 4
#define CAL_TURN_START_SPEED_TICKS 8
#define CAL_TURN_START_BOOST_MS 400U
#define CAL_STRAIGHT_MIN_DISTANCE_MM 700
#define CAL_STRAIGHT_MAX_DISTANCE_MM 1300
#define CAL_STRAIGHT_TIMEOUT_MS 35000U
#define CAL_CORNER_MIN_ACTIVE 6U
#define CAL_CORNER_CLEAR_MS 30U
#define CAL_CORNER_DEBOUNCE_MS 8U
#define CAL_TURN_TARGET_MDEG 360000
#define CAL_TURN_WRONG_DIRECTION_MDEG 15000
#define CAL_TURN_MAX_WHEEL_DISTANCE_MM 1600
#define CAL_TURN_SETTLE_MS 150U
#define CAL_TURN_TIMEOUT_MS 15000U
#define CAL_OFFSET_LINE_LOST_MS 20U
#define CAL_OFFSET_MAX_DISTANCE_MM 500
#define CAL_OFFSET_TIMEOUT_MS 12000U

#endif
